"""empty message

Revision ID: 544f1b8bde1e
Revises: 5ac180abfaf7
Create Date: 2015-07-12 21:17:03.233038

"""

# revision identifiers, used by Alembic.
revision = '544f1b8bde1e'
down_revision = '5ac180abfaf7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
